### ISSUE TITLE
[Bug] Disconnect is not working.

### ISSUE THREAD

**Issue by bnt4** [AntTheAntster/Useful-Classes#1]
The disconnect method in the MySQL class won't work, since you check for

```java
if(!isConnected()) {
    // Disconnect
}
```

and not 

```java
if(isConnected()) {
    // Disconnect
}
```

Please remove the `!` to fix it.

**Comment by AntTheAntster** [comment]
Ah yes, simple mistake, whoops, it is fixed now thanks :)
